openapi: 3.0.0
info:
  version: 0.0-oas3
  title: specfile
  description: >-
    A simple service to use heart failure predicter
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /predict/{array}:
    get:
      tags:
        - PRED
      operationId: prediction.my_prediction
      description: Returns prediction
      parameters:
        - in: path
          name: array
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'Heart Failure info, or add more text'
servers:
  - url: 'http://localhost:8080/engr-222'
